export const actionTypes = {
  REQUEST_MESSAGES: 'REQUEST_MESSAGES',
  RECEIVED_MESSAGES: 'RECEIVED_MESSAGES',
  ERROR_MESSAGES: 'ERROR_MESSAGES',
  
  REQUEST_POST_MESSAGE: 'REQUEST_POST_MESSAGE',
  RECEIVED_POST_MESSAGE: 'RECEIVED_POST_MESSAGE',
  ERROR_POST_MESSAGE: 'ERROR_POST_MESSAGE',
  
};